Added GitHub Actions to automate packaging
OpenRA/SDL2-CS pull request #6
Opened 2023-04-23 21:44 UTC by penev92

Same as https://github.com/OpenRA/Eluant/pull/5 and https://github.com/OpenRA/OpenAL-CS/pull/4:

Adding 3 workflows to automate compiling of native dependencies, compiling of the C# wrapper library and packaging it all into a NuGet package and publishing that.

The native binary compilation steps are all taken from @pchote's https://github.com/pchote/native-dependencies

P.S.: For results of a successful run see https://github.com/penev92/SDL2-CS/actions/runs/4780366537 and https://www.nuget.org/packages/OpenRA-SDL2-CS/1.0.38-a9

P.P.S.: I added a few improvements over the OpenAL-CS PR which I plan on porting back later to https://github.com/OpenRA/OpenAL-CS and https://github.com/OpenRA/Eluant.

2023-04-23 21:52 UTC, pchote approved these changes
macos-arm64 and linux-arm64 both seem to work using the -a9 nuget.

2023-04-24 07:46 UTC, abcdefg30 approved these changes

2023-04-24 07:46 UTC, abcdefg30 commented on .github/workflows/build-natives.yml
> +    # to ensure backwards compatibility of the combiled binaries.
```suggestion
    # to ensure backwards compatibility of the compiled binaries.
```

2023-04-24 08:17 UTC, Mailaender commented
I suggest you download the `libEGL*.dll` from Google inside the workflow so we know where they are coming from. Then you also don't have binaries in git which is bad practice.

2023-04-24 08:18 UTC, Mailaender requested changes
I suggest you download the `libEGL*.dll` from Google inside the workflow so we know where they are coming from. Then you also don't have binaries in git which is bad practice.

2023-04-24 18:50 UTC, penev92 commented
Like I said I would prefer that as well, but do we have a way to do that?

2023-04-25 08:45 UTC, Mailaender commented
Like I said yesterday, either extract from [Chromium ZIPs](https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1135051/chrome-win.zip) during the Workflow or [build yourself](https://chromium.googlesource.com/angle/angle/+/master/doc/DevSetup.md).

2023-04-26 13:16 UTC, penev92 commented
The links with the zips that you gave me on Discord had Chromium releases up until 2018!
As for compiling it ourselves - I did read the "instructions" and they made sure it was as convoluted as possible. It's out of my depth and I don't want to spend weeks struggling with it.

2023-04-26 18:25 UTC, Mailaender commented
The link I gave you above is from https://chromium.woolyss.com/download/ which is dated to yesterday.

2023-04-27 11:19 UTC, penev92 commented
Thanks!
Here is the result of the extracting - you can see execution time, the zipped artifact and the used workflow file: https://github.com/penev92/SDL2-CS/actions/runs/4819116799
I will update the PR when I have some time.

2023-05-02 08:13 UTC, penev92 commented
Fixed typos, removed ANGLE libraries for Windows and added downloading of Chromium to extract them.

2023-05-02 11:24 UTC, penev92 commented
Here is the run for `1.0.38-a10`: https://github.com/penev92/SDL2-CS/actions/runs/4860223694
Link to NuGet package: https://www.nuget.org/packages/OpenRA-SDL2-CS/1.0.38-a10

2023-05-02 16:15 UTC, Mailaender approved these changes

2023-05-02 16:43 UTC, merged